emulator mockdata loading
habits-together/server pull request #1
Opened 2024-12-15 10:16 UTC by AnkushSarkar10

2024-12-15 10:17 UTC, AnkushSarkar10 commented
* **#1** <a href="https://app.graphite.dev/github/pr/habits-together/server/1?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/habits-together/server/1?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-10 18:45 UTC, owengretzinger requested changes
I got it running but some things weren't clear:

There's a package-lock.json in the top-level but no package.json. The README just says to do `npm install` but that doesn't work in the top level. I'm assuming it's supposed to be inside `/functions` but it doesn't specify that.

Furthermore, do we really need to export the `GOOGLE_APPLICATION_CREDENTIALS`? Can't we just somehow automatically link it?

And what's `ts-node` for? Can we just install it locally?

2025-01-10 18:45 UTC, owengretzinger commented on functions/package.json
> +    "seed": "ts-node .\\src\\seedFirestore.ts",
Doesn't work on Mac

```suggestion
    "seed": "ts-node ./src/seedFirestore.ts",
```

2025-01-27 02:49 UTC, owengretzinger approved these changes

2025-01-27 02:50 UTC, owengretzinger commented
### Merge activity

* **Jan 26, 9:49 PM EST**: [Graphite](https://app.graphite.dev/github/pr/habits-together/server/1) couldn't merge this PR because it failed for an unknown reason (Merge commits are not allowed on this repository).

2025-01-27 02:51 UTC, merged